import { Menu } from './js/Menu'
import { MainConatainer } from './js/MainContainer'
import { Cards } from './js/Cards'
import { CategoryPage } from './js/CategoryPage'
import { PlayMode } from './js/PlayMode'